name: pharmacy_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.3
  go_router: ^15.1.2
  intl: ^0.20.2
  equatable: ^2.0.7
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  connectivity_plus: ^6.1.4
  bloc: ^9.0.0
  responsive_builder: ^0.7.1
  json_annotation: ^4.9.0
  firebase_core: ^3.13.0
  provider: ^6.1.5
  flutter_bloc: ^9.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  


flutter:
  uses-material-design: true
  assets:
    - assets/images/

